export const authTypes = {
  OAUTH_STARTING: "AUTH_STARTING",
  OAUTH_SUCCESS: "AUTH_SUCCESS",
  OAUTH_FAIL: "AUTH_FAIL",
  OAUTH_LOGOUT: "AUTH_LOGOUT",
  ONBRD_STARTING: "ONBRD_STARTING",
  ONBRD_SUCCESS: "ONBRD_SUCCESS",
  ONBRD_FAIL: "ONBRD_FAIL",
  USR_UPDATE_STARTING: "USR_UPDATE_STARTING",
  USR_UPDATE_SUCCESS: "USR_UPDATE_SUCCESS",
  USR_UPDATE_FAIL: "USR_UPDATE_FAIL"
};
export const rideTypes = {
  FIND_DRIVERS_STARTING: "FIND_DRIVERS_STARTING",
  FIND_DRIVERS_SUCCESS: "FIND_DRIVERS_SUCCESS",
  FIND_DRIVERS_FAIL: "FIND_DRIVERS_FAIL",
  CREATE_RIDE_STARTING: "CREATE_RIDE_STARTING",
  CREATE_RIDE_SUCCESS: "CREATE_RIDE_SUCCESS",
  CREATE_RIDE_FAIL: "CREATE_RIDE_FAIL",
  SELECT_DRIVER_START: "SELECT_DRIVER_START",
  SELECT_DRIVER_SUCCESS: " SELECT_DRIVER_SUCCESS",
  SELECT_DRIVER_FAIL: " SELECT_DRIVER_FAIL"
};
