export const authTypes = {
  OAUTH_STARTING: "AUTH_STARTING",
  OAUTH_SUCCESS: "AUTH_SUCCESS",
  OAUTH_FAIL: "AUTH_FAIL",
  OAUTH_LOGOUT: "AUTH_LOGOUT",
  ONBRD_STARTING: "ONBRD_STARTING",
  ONBRD_SUCCESS: "ONBRD_SUCCESS",
  ONBRD_FAIL: "ONBRD_FAIL"
};
